first steps in logrefactoring

diff --git a/usr/sbin/drlm b/usr/sbin/drlm
--- a/usr/sbin/drlm
+++ b/usr/sbin/drlm
@@ -22,38 +22,66 @@
 # Didac Oliveira  <didac at brainupdaters dot net> [DO]
 # Pau Roura	  <pau at brainupdaters dot net> [PR]
 
+# Usually functions belong to the library scripts (i.e. $SHARE_DIR/lib/*.sh),
+# but these 2 are exceptions on the rule because the complementary global functions
+# to get and apply bash flags and options commands are needed from the very beginning
+# (the usual functions are sourced at "Include functions" below):
+function get_bash_flags_and_options_commands () {
+    # Output bash commands that set the currently set flags
+    # in reverse ordering to have "set ... xtrace" (i.e. "set +/- x") first
+    # so that this flag is set first via apply_bash_flags_and_options_commands
+    # which results better matching logging output in debugscript mode:
+    set +o | tac | tr '\n' ';'
+    # Output bash commands that set the currently set options:
+    shopt -p | tr '\n' ';'
+}
+# This function exists only to provide a syntactically matching counterpart of get_bash_flags_and_options_commands:
+function apply_bash_flags_and_options_commands () {
+    # Must be called with $1 that is the output of a previous get_bash_flags_and_options_commands:
+    eval "$1"
+}
+# At the very beginning save initial bash flags and options in a global readonly variable
+# so that exactly the initial bash flags and options can be restored if needed via
+#   apply_bash_flags_and_options_commands "$INITIAL_BASH_FLAGS_AND_OPTIONS_COMMANDS"
+readonly INITIAL_BASH_FLAGS_AND_OPTIONS_COMMANDS="$( get_bash_flags_and_options_commands )"
 
 # Versioning
-PRODUCT="Disaster Recovery Linux Manager"
-PROGRAM=${0##*/}
-VERSION=2.4.0
-RELEASE_DATE="Git"
+readonly PRODUCT="Disaster Recovery Linux Manager"
+readonly PROGRAM=${0##*/}
+readonly VERSION=2.4.0
+readonly RELEASE_DATE="Git"
 
-STARTTIME=$SECONDS
+readonly STARTTIME=$SECONDS
 
 # Allow workflows to set the exit code to a different value.
 EXIT_CODE=0
 
 # Find out if we're running from checkout
-SCRIPT_FILE="$(readlink -f $(type -p "$0" || echo "$0"))"
+readonly SCRIPT_FILE="$(readlink -f $(type -p "$0" || echo "$0"))"
 if [[ "$SCRIPT_FILE" != "$(readlink -f /usr/sbin/$PROGRAM)" ]]; then
     DRLM_DIR_PREFIX=${SCRIPT_FILE%/usr/sbin/$PROGRAM}
 fi
+readonly DRLM_DIR_PREFIX
 
 # Program directories - they must be set here. Everything else is then dynamic
 SHARE_DIR="$DRLM_DIR_PREFIX/usr/share/drlm"
 CONFIG_DIR="$DRLM_DIR_PREFIX/etc/drlm"
 LOG_DIR="$DRLM_DIR_PREFIX/var/log/drlm"
-CMD_OPTS=( "$@" )
+# readonly CMD_OPTS=( "$@" )
+
+# The current working directory when this script (usr/sbin/drlm) is launched
+# is also the working directory of all the other scripts and config files
+# that get sourced via the Source() function in lib/framework-functions.sh
+readonly WORKING_DIR="$( pwd )"
 
 # initialize defaults
-STEPBYSTEP=
-SIMULATE=
-VERBOSE=
-DEBUG=
+STEPBYSTEP=""
+SIMULATE=""
+VERBOSE=""
+DEBUG=""
 
 # split the parameters into two parts, one for the DRLM and one for the workflow
-ARGUMENTS=("$@")
+readonly ARGUMENTS=( "$@" )
 NUMERO=${#ARGUMENTS[@]}
 declare -a PARAMETRES1
 declare -a PARAMETRES2
@@ -92,6 +120,7 @@ if (( $? != 0 )); then
 	exit 1
 fi
 
+readonly OPTS
 eval set -- "$OPTS"
 while true; do
 	case "$1" in
@@ -126,6 +155,10 @@ fi
 set -- ${PARAMETRES2[@]}
 ARGS=( "$@" )
 
+readonly ARGS
+readonly DEBUG DEBUGSCRIPTS
+readonly SIMULATE STEPBYSTEP
+
 # Make sure we have the necessary paths (eg. in cron), /sbin will be the first path to search.
 # some needed binaries are in /lib/udev or /usr/lib/udev
 for path in /usr/bin /bin /usr/sbin /sbin; do
@@ -143,7 +176,16 @@ if [[ "$(id --user)" != "0" ]]; then
 fi
 
 # set some bash options
+# With nullglob set when e.g. for foo*bar no file matches are found, then foo*bar is removed
+# (e.g. "ls foo*bar" becomes plain "ls" without "foo*bar: No such file or directory" error).
+# The extglob shell option enables several extended pattern matching operators.
 shopt -s nullglob extglob
+# Save the current default bash flags and options in a global readonly variable
+# so that exactly the default bash flags and options can be restored if needed via
+#   apply_bash_flags_and_options_commands "$DEFAULT_BASH_FLAGS_AND_OPTIONS_COMMANDS"
+readonly DEFAULT_BASH_FLAGS_AND_OPTIONS_COMMANDS="$( get_bash_flags_and_options_commands )"
+
+# Forget all remembered full pathnames of commands:
 hash -r
 
 # make sure that we use only english
@@ -152,9 +194,20 @@ export LC_CTYPE=C LC_ALL=C LANG=C
 # set umask
 umask 0022
 
+####################################################
+### TODO --- Aqui hi ah el curro dels logs
+####################################################
+####################################################
+####################################################
 # Logfile name
 TIMESTAMP=$(date +"%Y%m%d.%H%M%S.%4N")
 LOGFILE="$LOG_DIR/drlm-$HOSTNAME-$WORKFLOW.$TIMESTAMP.log"
+
+if [ "$WORKFLOW" == "sched" ]; then
+  LOGFILE="$LOG_DIR/drlm-$WORKFLOW.log"
+elif [[ "$WORKFLOW" =~ ^(listnetwork|listclient|listbackup|listjob|bkpmgr)$ ]]; then
+  LOGFILE="$LOG_DIR/drlm.log"
+fi
 
 # include default config
 source $SHARE_DIR/conf/default.conf
@@ -175,8 +228,20 @@ if ! has_binary pidof; then
 	exit 1
 fi
 
-mkdir -p $LOG_DIR
-exec 2>"$LOGFILE" || echo "ERROR: Could not create $LOGFILE" >&2
+mkdir -p $LOG_DIR || echo "ERROR: Could not create $LOG_DIR" >&2
+
+if test "$DEBUG" ; then
+    exec 2>>"$LOGFILE"
+else
+    exec 2>> "$LOGFILE"
+fi
+
+# exec 2>> "$LOGFILE" || echo "ERROR: Could not create $LOGFILE" >&2
+Log ""
+Log ""
+####################################################
+####################################################
+####################################################
 
 case "$WORKFLOW" in
 	(help) ;;
